const express = require("express");
const admissionClassificationController = require("../controllers/admissionClassificationController");
const router = express.Router();
const { authenticateToken, verifyPrinicipal } = require("../middleware/auth"); 
router.post("/create", authenticateToken, verifyPrinicipal,admissionClassificationController.createAdmissionClassification);
router.delete("/delete/:id", authenticateToken, verifyPrinicipal,admissionClassificationController.deleteAdmissionClassification);
router.get("/academic_session/:academic_session", admissionClassificationController.getAcademicSessionClassifications);
router.put("/open/:id", authenticateToken, verifyPrinicipal,admissionClassificationController.openAdmission);
router.put("/close/:id", authenticateToken, verifyPrinicipal,admissionClassificationController.closeAdmission);
module.exports = router;
