export const API_CONFIG = {
    baseURL: 'http://localhost:5000',
    endpoints: {
        getDepartments: '/api/departments/',
        createDepartment: '/api/departments/create',
        updateDepartment: '/api/departments/update',
        deleteDepartment: '/api/departments/delete',
        getTeachers: '/api/teachers/',
        createTeacher: '/api/teachers/create',
        updateTeacher: '/api/teachers/update',
        deleteTeacher: '/api/teachers/delete',
        getSubjects: '/api/subjects/',
        createSubject: '/api/subjects/create',
        updateSubject: '/api/subjects/update',
        deleteSubject: '/api/subjects/delete',
        getGrades: '/api/grades/',
        getCurricula: '/api/curricula/',
        createCurriculum: '/api/curricula/create',
        updateCurriculum: '/api/curricula/update',
        deleteCurriculum: '/api/curricula/delete',
        addGrade: '/api/curricula/add-grade',
        removeGrade: '/api/curricula/remove-grade',
        addSubject: '/api/curricula/add-subject',
        removeSubject: '/api/curricula/remove-subject'
    },
};