export const API_CONFIG = {
    baseURL: 'http://localhost:5000',
    endpoints: {
        getDepartments: '/api/departments/',
        createDepartment: '/api/departments/create',
        updateDepartment: '/api/departments/update',
        deleteDepartment: '/api/departments/delete',
        getTeachers: '/api/teachers/',
        createTeacher: '/api/teachers/create',
        updateTeacher: '/api/teachers/update',
        deleteTeacher: '/api/teachers/delete',
        getSubjects: '/api/subjects/',
        createSubject: '/api/subjects/create',
        updateSubject: '/api/subjects/update',
        deleteSubject: '/api/subjects/delete',
        getGrades: '/api/grades/',
        getCurricula: '/api/curricula/',
        createCurriculum: '/api/curricula/create',
        updateCurriculum: '/api/curricula/update',
        deleteCurriculum: '/api/curricula/delete',
        addGrade: '/api/curricula/add-grade',
        removeGrade: '/api/curricula/remove-grade',
        getCurriculumGradesByCurriculum:'/api/curriculum-grade/curriculum',
        createCurriculumGrade: '/api/curriculum-grade/create',
        deleteCurriculumGrade: '/api/curriculum-grade/delete',
        getGradeSubjectsByCurriculumGrade:'/api/grade-subject/curriculum-grade',
        createGradeSubject: '/api/grade-subject/create',
        deleteGradeSubject: '/api/grade-subject/delete',
        addSubject: '/api/curricula/add-subject',
        removeSubject: '/api/curricula/remove-subject',     
        getAdmissionClassifications: '/api/admission-classifications/',
        createAdmissionClassification: '/api/admission-classifications/create',
        updateAdmissionClassification: '/api/admission-classifications/update',
        deleteAdmissionClassification: '/api/admission-classifications/delete',
        getAcademicSessionClassifications:'/api/admission-classifications/findByAcademicSession',
        createClassificationGrade: '/api/classification-grades/create',
        updateClassificationGrade: '/api/classification-grades/update',
        deleteClassificationGrade: '/api/classification-grades/delete',
        getClassificationGradesByClassification:'/api/classification-grades/admission_classification'
    },
};